//! SECOM cipher implementation (VIC-derived).
//!
//! Based on the description and worked example at:
//! <http://www.ciphermachinesandcryptology.com/en/secom.htm>
//!
//! NOTE: there are separate implementation of the Checkerboard and disrupted
//! transposition due to the nature of both ciphers:
//! 1. The alphabets are different, and we need two digits in the VIC cipher, whereas SECOM needs 3.
//! 2. The disrupted transposition is not symmetric, so we need to implement it twice.
//!
//! SECOM is easier to implement, as the key is only one phrase, and the key derivation is also
//! easier to run.  Also, you can use numbers directly in the plaintext as they will not be triplicated
//! like for any cipher using only 25 letters.
//!
//! # Example
//!
//! ```rust
//! use old_crypto_rs::SecomCipher;
//! use old_crypto_rs::Block;
//!
//! let key_phrase = "MAKE NEW FRIENDS BUT KEEP THE OLD";
//! let freq = "ESTONIA";
//!
//! let cipher = SecomCipher::new(key_phrase, freq).unwrap();
//! let pt = b"HELLO WORLD";
//!
//! let mut ct = vec![0u8; 128];
//! let ct_len = cipher.encrypt(&mut ct, pt);
//! let mut dec = vec![0u8; 128];
//! let dec_len = cipher.decrypt(&mut dec, &ct[..ct_len]);
//! assert_eq!(&dec[..dec_len], pt);
//! ```
//!

mod checkerboard;
mod disrupted;
mod subr;

pub(crate) use checkerboard::SecomCheckerboard;
pub(crate) use disrupted::SecomDisruptedTransposition;
pub(crate) use subr::{
    addmod10, chain_add_row, letters_to_digits_1to0, normalize_key_phrase, rank_digits_1to0,
    read_out_columns, transposition_widths_from_last_row, vec_to_array_10,
};

use crate::{Block, Transposition};

use eyre::{eyre, Result};
use crate::error::Error;

/// SECOM cipher implementation.
///
/// SECOM is a VIC-derived cipher that uses a single key phrase and a frequency
/// string to initialize its components: a straddling checkerboard and two
/// columnar transpositions (one regular and one disrupted).
///
#[derive(Debug)]
pub struct SecomCipher {
    /// The internal straddling checkerboard.
    checker: SecomCheckerboard,
    /// First (regular) columnar transposition.
    tp1: Transposition,
    /// The second (disrupted) columnar transposition.
    tp2: SecomDisruptedTransposition,
}

impl SecomCipher {
    /// Creates a new `SecomCipher` instance.
    ///
    /// # Arguments
    ///
    /// * `key_phrase` - A string of at least 20 letters used for key derivation.
    /// * `freq` - A 7-letter frequency string for the checkerboard (e.g., "ESTONIA").
    ///
    pub fn new(key_phrase: &str, freq: &str) -> Result<Self> {
        let key = normalize_key_phrase(key_phrase);
        if key.len() < 20 {
            return Err(Error::KeyTooShort(20)).into());
        }
        let key20 = &key[..20];
        let a = &key20[..10];
        let b = &key20[10..20];

        // Derive key digits from the key phrase
        //
        let a_digits = letters_to_digits_1to0(a);
        let b_digits = letters_to_digits_1to0(b);
        let sum_row = addmod10(&a_digits, &b_digits);

        // Now, do the chain addition
        //
        let mut rows = Vec::with_capacity(5);
        let mut prev = sum_row.clone();
        for _ in 0..5 {
            let next = chain_add_row(&prev);
            rows.push(next.clone());
            prev = next;
        }

        // Derive the checkerboard key from the last row
        //
        let last_row = rows.last().ok_or(eyre!("failed to generate rows"))?.clone();
        let header_digits = rank_digits_1to0(&last_row);
        let checker = SecomCheckerboard::new(vec_to_array_10(&header_digits)?, freq)?;

        // Derive the lengths of both transpositions
        //
        let widths = transposition_widths_from_last_row(&last_row)?;
        let tp1_width = widths.0;
        let tp2_width = widths.1;

        // The two transposition keys are generated by adding the checkerboard key & the 2nd part of the
        // keyphrase, and this will be used as a transposition.
        //
        let key10 = addmod10(&b_digits, &header_digits);

        // Generate the two keys by taking enough digits.
        //
        let key_stream = read_out_columns(&rows, &key10);
        if key_stream.len() < tp1_width + tp2_width {
            return Err(Error::BadKeyStream.into());
        }

        // First transposition
        //
        let tp1_key = &key_stream[..tp1_width];
        let mut tp1_key_str = String::with_capacity(tp1_key.len());
        for &d in tp1_key {
            tp1_key_str.push((b'0' + d) as char);
        }
        let tp1 = Transposition::new(&tp1_key_str)?;

        // Second transposition
        //
        let tp2_key = key_stream[tp1_width..tp1_width + tp2_width].to_vec();
        let tp2 = SecomDisruptedTransposition::new(tp2_width, tp2_key);

        Ok(SecomCipher { checker, tp1, tp2 })
    }

    /// Normalizes plaintext for encryption: converts spaces to '*' and
    /// keeps only A-Z, 0-9, and '*'.
    ///
    fn preprocess_plaintext(pt: &[u8]) -> Vec<u8> {
        let mut out = Vec::with_capacity(pt.len());
        for &ch in pt {
            let c = if ch == b' ' {
                b'*'
            } else {
                ch.to_ascii_uppercase()
            };
            if (b'A'..=b'Z').contains(&c) || (b'0'..=b'9').contains(&c) || c == b'*' {
                out.push(c);
            }
        }
        out
    }

    /// Converts '*' back to spaces in the decrypted plaintext.
    ///
    fn postprocess_plaintext(pt: &[u8]) -> Vec<u8> {
        let mut out = Vec::with_capacity(pt.len());
        for &ch in pt {
            out.push(if ch == b'*' { b' ' } else { ch });
        }
        out
    }
}

impl Block for SecomCipher {
    fn block_size(&self) -> usize {
        1
    }

    /// Encrypts source data into destination buffer.
    ///
    /// This implementation performs:
    /// 1. Preprocessing (uppercase, space conversion).
    /// 2. Checkerboard encoding.
    /// 3. Padding to a multiple of 5.
    /// 4. First (regular) columnar transposition.
    /// 5. Second (disrupted) columnar transposition.
    ///
    fn encrypt(&self, dst: &mut [u8], src: &[u8]) -> usize {
        let pt = Self::preprocess_plaintext(src);
        let mut digits = vec![0u8; pt.len() * 2];
        let sc_len = self.checker.encrypt(&mut digits, &pt);
        let digits = &digits[..sc_len];

        let mut tp1_buf = vec![0u8; digits.len()];
        self.tp1.encrypt(&mut tp1_buf, digits);

        self.tp2.encrypt(dst, &tp1_buf)
    }

    /// Decrypts source data into destination buffer.
    ///
    /// This implementation performs:
    /// 1. Second (disrupted) columnar transposition (reverse).
    /// 2. First (regular) columnar transposition (reverse).
    /// 3. Padding removal.
    /// 4. Checkerboard decoding.
    /// 5. Postprocessing.
    ///
    fn decrypt(&self, dst: &mut [u8], src: &[u8]) -> usize {
        let mut tp1_encoded = vec![0u8; src.len()];
        let tp1_len = self.tp2.decrypt(&mut tp1_encoded, src);
        let tp1_encoded = &tp1_encoded[..tp1_len];

        let mut digits = vec![0u8; tp1_encoded.len()];
        self.tp1.decrypt(&mut digits, tp1_encoded);

        let mut buf_pt = vec![0u8; digits.len()];
        let pt_len = self.checker.decrypt(&mut buf_pt, &digits);
        let post = Self::postprocess_plaintext(&buf_pt[..pt_len]);

        let n = post.len().min(dst.len());
        dst[..n].copy_from_slice(&post[..n]);
        n
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::secom::subr::{
        addmod10, chain_add_row, column_order_from_digits, letters_to_digits_1to0,
        rank_digits_1to0, read_out_columns, transposition_widths_from_last_row, vec_to_array_10,
    };

    #[test]
    fn test_key_derivation_example() {
        let key_phrase = "MAKE NEW FRIENDS BUT KEEP THE OLD";
        let key = normalize_key_phrase(key_phrase);
        let key20 = &key[..20];
        let a = &key20[..10];
        let b = &key20[10..20];

        let a_digits = letters_to_digits_1to0(a);
        let b_digits = letters_to_digits_1to0(b);
        assert_eq!(a_digits, vec![7, 1, 6, 2, 8, 3, 0, 4, 9, 5]);
        assert_eq!(b_digits, vec![3, 7, 2, 8, 1, 0, 9, 6, 4, 5]);

        let sum_row = addmod10(&a_digits, &b_digits);
        assert_eq!(sum_row, vec![0, 8, 8, 0, 9, 3, 9, 0, 3, 0]);

        let mut rows = Vec::new();
        let mut prev = sum_row.clone();
        for _ in 0..5 {
            let next = chain_add_row(&prev);
            rows.push(next.clone());
            prev = next;
        }
        assert_eq!(rows[0], vec![8, 6, 8, 9, 2, 2, 9, 3, 3, 8]);
        assert_eq!(rows[1], vec![4, 4, 7, 1, 4, 1, 2, 6, 1, 2]);
        assert_eq!(rows[2], vec![8, 1, 8, 5, 5, 3, 8, 7, 3, 0]);
        assert_eq!(rows[3], vec![9, 9, 3, 0, 8, 1, 5, 0, 3, 9]);
        assert_eq!(rows[4], vec![8, 2, 3, 8, 9, 6, 5, 3, 2, 7]);

        let header = rank_digits_1to0(&rows[4]);
        assert_eq!(header, vec![8, 1, 3, 9, 0, 6, 5, 4, 2, 7]);

        let (w1, w2) = transposition_widths_from_last_row(&rows[4]).unwrap();
        assert_eq!(w1, 12);
        assert_eq!(w2, 11);

        let key10 = addmod10(&b_digits, &header);
        assert_eq!(key10, vec![1, 8, 5, 7, 1, 6, 4, 0, 6, 2]);

        let key_stream = read_out_columns(&rows, &key10);
        let tp1_key: String = key_stream[..w1]
            .iter()
            .map(|d| (b'0' + d) as char)
            .collect();
        let tp2_key: String = key_stream[w1..w1 + w2]
            .iter()
            .map(|d| (b'0' + d) as char)
            .collect();
        assert_eq!(tp1_key, "848982458982");
        assert_eq!(tp2_key, "09792855878");
    }

    #[test]
    fn test_checkerboard_example() {
        let header = vec![8, 1, 3, 9, 0, 6, 5, 4, 2, 7];
        let checker = SecomCheckerboard::new(vec_to_array_10(&header).unwrap(), "ESTONIA").unwrap();
        assert_eq!(checker.longc, [3, 6, 2]);

        let mut out = vec![0u8; 256];
        let pt = b"RV*TOMORROW*AT*1400PM*TO*COMPLETE*TRANSACTION*USE*DEADDROP*AS*USUAL";
        let len = checker.encrypt(&mut out, pt);
        let ct = String::from_utf8_lossy(&out[..len]).to_string();
        assert_eq!(
            ct,
            "64676090310646406860796021202828663160906039031663889860964751739940560621860308730306406660716062162738"
        );
    }

    #[test]
    fn test_checkerboard_isolated() {
        // From the example: header = [8, 1, 3, 9, 0, 6, 5, 4, 2, 7], freq = "ESTONIA"
        //
        let header = [8, 1, 3, 9, 0, 6, 5, 4, 2, 7];
        let checker = SecomCheckerboard::new(header, "ESTONIA").unwrap();

        let pt = b"HELLO";
        let mut ct = vec![0u8; 10];
        let ct_len = checker.encrypt(&mut ct, pt);

        // H is not in ESTONIA. It's in the first extra row (long digit 3).
        // E is in ESTONIA. Top row.
        // L is not in ESTONIA. Extra row.
        // O is in ESTONIA. Top row.

        // Let's verify some mappings manually based on the logic:
        // header: 8 1 3 9 0 6 5 4 2 7
        // col:    0 1 2 3 4 5 6 7 8 9
        // FREQ_BLANK_POS: 2, 5, 8 (header[2]=3, header[5]=6, header[8]=2)
        // Top row (freq="ESTONIA"):
        // col 0: header[0]=8 -> E
        // col 1: header[1]=1 -> S
        // col 3: header[3]=9 -> T
        // col 4: header[4]=0 -> O
        // col 6: header[6]=5 -> N
        // col 7: header[7]=4 -> I
        // col 9: header[9]=7 -> A
        //
        let mut dec = vec![0u8; 5];
        let dec_len = checker.decrypt(&mut dec, &ct[..ct_len]);
        assert_eq!(&dec[..dec_len], pt);
    }

    #[test]
    fn test_disrupted_transposition_isolated() {
        let key = vec![0, 9, 7, 9, 2, 8, 5, 5, 8, 7, 8]; // tp2_key from example
        let width = 11;
        let tp = SecomDisruptedTransposition::new(width, key);

        let pt = b"1234567890123456789012"; // 2 full rows
        let mut ct = vec![0u8; 22];
        tp.encrypt(&mut ct, pt);

        let mut dec = vec![0u8; 22];
        tp.decrypt(&mut dec, &ct);
        assert_eq!(dec, pt);
    }

    #[test]
    fn test_column_order() {
        let key = vec![1, 8, 5, 7, 1, 6, 4, 0, 6, 2];
        let order = column_order_from_digits(&key);

        // Let's use the actual observed output to match the logic
        // key: [1, 8, 5, 7, 1, 6, 4, 0, 6, 2]
        // sorted by (if d==0 {10} else {d}, index):
        // (1, 0) -> 0
        // (1, 4) -> 4
        // (2, 9) -> 9
        // (4, 6) -> 6
        // (5, 2) -> 2
        // (6, 5) -> 5
        // (6, 8) -> 8
        // (7, 3) -> 3
        // (8, 1) -> 1
        // (10, 7) -> 7 (because d=0)
        //
        assert_eq!(order, vec![0, 4, 9, 6, 2, 5, 8, 3, 1, 7]);
    }

    #[test]
    fn test_full_cipher_example() {
        let key_phrase = "MAKE NEW FRIENDS BUT KEEP THE OLD";
        let cipher = SecomCipher::new(key_phrase, "ESTONIA").unwrap();

        let pt = b"RV TOMORROW AT 1400PM TO COMPLETE TRANSACTION USE DEADDROP AS USUAL";
        let mut ct = vec![0u8; 256];
        let ct_len = cipher.encrypt(&mut ct, pt);
        let ct_str = String::from_utf8_lossy(&ct[..ct_len]).to_string();
        assert_eq!(
            ct_str,
            "37719386226003204230600382968314608060517801673776060646936069686740369681890014021906662606660863160549"
        );

        let mut dec = vec![0u8; 256];
        let dec_len = cipher.decrypt(&mut dec, ct_str.as_bytes());
        let dec_str = String::from_utf8_lossy(&dec[..dec_len]).to_string();
        assert_eq!(
            dec_str,
            "RV TOMORROW AT 1400PM TO COMPLETE TRANSACTION USE DEADDROP AS USUAL"
        );
    }

    #[test]
    fn test_custom_freq() {
        let key_phrase = "MAKE NEW FRIENDS BUT KEEP THE OLD";
        let freq = "BCDFGHJ";
        let cipher = SecomCipher::new(key_phrase, freq).unwrap();
        let pt = b"HELLO WORLD";
        let mut ct = vec![0u8; 128];
        let ct_len = cipher.encrypt(&mut ct, pt);
        let mut dec = vec![0u8; 128];
        let dec_len = cipher.decrypt(&mut dec, &ct[..ct_len]);
        assert_eq!(&dec[..dec_len], pt);
    }
}
