use std::marker::PhantomData;
use crate::helpers::{TranspositionMask, to_numeric};
use crate::Block;
use crate::error::Error;
use eyre::Result;

/// Generic disrupted transposition cipher using a masking policy.
///
/// This cipher implements a columnar transposition where certain cells are masked
/// (filled later) according to a policy defined by the `TranspositionMask` trait.
/// The grid is filled in two phases: first the non-masked cells, then the masked cells.
///
/// # Type Parameters
///
/// * `P` - A type implementing `TranspositionMask` that defines which cells are masked
///
pub struct Disrupted<P: TranspositionMask> {
    #[allow(dead_code)]
    key: String,
    tkey: Vec<u8>,
    tkey_order: Vec<usize>,
    _policy: PhantomData<P>,
}

impl<P: TranspositionMask> Disrupted<P> {
    /// Creates a new disrupted transposition cipher.
    ///
    /// The key is converted to a numeric representation where each character's position
    /// in alphabetical order determines its rank.
    ///
    /// # Arguments
    ///
    /// * `key` - The key string used for transposition. Must not be empty.
    ///
    /// # Returns
    ///
    /// Returns `Ok(Disrupted)` if the key is valid, or an error if the key is empty.
    ///
    /// # Examples
    ///
    /// ```
    /// use old_crypto_rs::transposition::Disrupted;
    /// use old_crypto_rs::helpers::TranspositionMask;
    ///
    /// // Define a simple mask policy
    /// struct MyMask;
    /// impl TranspositionMask for MyMask {
    ///     fn mask(width: usize, rows: usize, order: &[usize]) -> Vec<bool> {
    ///         vec![false; width * rows]
    ///     }
    /// }
    ///
    /// let cipher = Disrupted::<MyMask>::new("SUBWAY").unwrap();
    /// ```
    pub fn new(key: &str) -> Result<Self> {
        if key.is_empty() {
            return Err(Error::EmptyKeys.into());
        }
        let tkey = to_numeric(key);
        let klen = tkey.len();

        let mut tkey_order = vec![0; klen];
        for (i, item) in tkey_order.iter_mut().enumerate().take(klen) {
            *item = tkey.iter().position(|&x| x == i as u8).unwrap();
        }

        Ok(Disrupted {
            key: key.to_string(),
            tkey,
            tkey_order,
            _policy: PhantomData,
        })
    }

    /// Encrypts the source data using disrupted transposition.
    ///
    /// The encryption process works in three phases:
    ///
    /// 1. **Fill non-masked areas**: The plaintext is written into a grid row by row,
    ///    filling only the cells that are NOT masked according to the policy.
    ///
    /// 2. **Fill masked areas**: After the non-masked areas are filled, the remaining
    ///    plaintext continues filling the masked areas row by row.
    ///
    /// 3. **Read column by column**: The ciphertext is generated by reading the grid
    ///    column by column in the order specified by `tkey_order`.
    ///
    fn internal_encrypt(&self, src: &[u8], dst: &mut [u8]) -> usize {
        let klen = self.tkey.len();
        let len = src.len();
        if klen == 0 || len == 0 {
            return 0;
        }
        let rows = len.div_ceil(klen);
        let mask = P::mask(klen, rows, &self.tkey_order);

        let mut grid = vec![0u8; rows * klen];
        let mut src_idx = 0;

        // Phase 1: Fill non-masked areas row by row
        for r in 0..rows {
            let row_off = r * klen;
            for c in 0..klen {
                let idx = row_off + c;
                if idx < len && !mask[idx] && src_idx < len {
                    grid[idx] = src[src_idx];
                    src_idx += 1;
                }
            }
        }

        // Phase 2: Fill masked areas row by row
        for r in 0..rows {
            let row_off = r * klen;
            for c in 0..klen {
                let idx = row_off + c;
                if idx < len && mask[idx] && src_idx < len {
                    grid[idx] = src[src_idx];
                    src_idx += 1;
                }
            }
        }

        // Phase 3: Read out column by column according to tkey_order
        let mut dst_idx = 0;
        for &col in &self.tkey_order {
            for r in 0..rows {
                let idx = r * klen + col;
                if idx < len {
                    dst[dst_idx] = grid[idx];
                    dst_idx += 1;
                }
            }
        }

        len
    }

    /// Decrypts the source data using disrupted transposition.
    ///
    /// The decryption process reverses the encryption:
    ///
    /// 1. **Fill grid from columns**: The ciphertext is read column by column in the order
    ///    specified by `tkey_order`, filling the grid's cells.
    ///
    /// 2. **Read in two phases**: The plaintext is recovered by reading the grid in two phases:
    ///    - First phase: Read row by row from non-masked areas
    ///    - Second phase: Read row by row from masked areas
    ///
    fn internal_decrypt(&self, src: &[u8], dst: &mut [u8]) -> usize {
        let klen = self.tkey.len();
        let len = src.len();
        if klen == 0 || len == 0 {
            return 0;
        }
        let rows = len.div_ceil(klen);
        let mask = P::mask(klen, rows, &self.tkey_order);

        // Fill grid from src column by column
        let mut grid = vec![0u8; rows * klen];
        let mut src_idx = 0;
        for &col in &self.tkey_order {
            for r in 0..rows {
                let idx = r * klen + col;
                if idx < len && src_idx < len {
                    grid[idx] = src[src_idx];
                    src_idx += 1;
                }
            }
        }

        // Read out row by row, first non-masked then masked
        let mut dst_idx = 0;

        // Phase 1: Read non-masked areas
        for r in 0..rows {
            let row_off = r * klen;
            for c in 0..klen {
                let idx = row_off + c;
                if idx < len && !mask[idx] && dst_idx < len {
                    dst[dst_idx] = grid[idx];
                    dst_idx += 1;
                }
            }
        }

        // Phase 2: Read masked areas
        for r in 0..rows {
            let row_off = r * klen;
            for c in 0..klen {
                let idx = row_off + c;
                if idx < len && mask[idx] && dst_idx < len {
                    dst[dst_idx] = grid[idx];
                    dst_idx += 1;
                }
            }
        }

        len
    }
}

impl<P: TranspositionMask> Block for Disrupted<P> {
    fn block_size(&self) -> usize {
        self.tkey.len()
    }

    /// Encrypts source data into destination buffer using disrupted transposition.
    fn encrypt(&self, dst: &mut [u8], src: &[u8]) -> usize {
        self.internal_encrypt(src, dst)
    }

    /// Decrypts source data into destination buffer using disrupted transposition.
    fn decrypt(&self, dst: &mut [u8], src: &[u8]) -> usize {
        self.internal_decrypt(src, dst)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A simple no-mask policy for testing (behaves like regular transposition).
    struct NoMask;
    impl TranspositionMask for NoMask {
        fn mask(_width: usize, rows: usize, _order: &[usize]) -> Vec<bool> {
            vec![false; _width * rows]
        }
    }

    /// VIC-style triangular mask policy.
    ///
    /// Creates triangular areas starting at positions of ranks 0 and 1 in the key.
    struct VicMask;
    impl TranspositionMask for VicMask {
        fn mask(width: usize, rows: usize, order: &[usize]) -> Vec<bool> {
            let mut mask = vec![false; width * rows];

            // Find positions of ranks 0 and 1
            let pos0 = order[0];
            let pos1 = order[1];

            for r in 0..rows {
                let row_off = r * width;
                for c in 0..width {
                    // Mark cells in triangular areas
                    if (c >= pos0 + r || c >= pos1 + r) && c < width {
                        mask[row_off + c] = true;
                    }
                }
            }
            mask
        }
    }

    /// SECOM-style disrupted mask policy.
    ///
    /// Creates a more complex triangular pattern with cooldown periods.
    struct SecomMask;
    impl TranspositionMask for SecomMask {
        fn mask(width: usize, rows: usize, order: &[usize]) -> Vec<bool> {
            let mut mask = vec![false; rows * width];
            let mut tri_idx = 0usize;
            let mut row_offset = 0usize;
            let mut cooldown = 0usize;

            for r in 0..rows {
                let mut start = width;
                if cooldown > 0 {
                    cooldown -= 1;
                    if cooldown == 0 {
                        tri_idx += 1;
                        row_offset = 0;
                    }
                } else if tri_idx < order.len() {
                    let sc = order[tri_idx];
                    start = sc + row_offset;
                    if start < width {
                        row_offset += 1;
                        if sc + row_offset >= width {
                            cooldown = 1;
                        }
                    } else {
                        cooldown = 1;
                    }
                }

                if start < width {
                    let row_off = r * width;
                    for c in start..width {
                        mask[row_off + c] = true;
                    }
                }
            }
            mask
        }
    }

    #[test]
    fn test_disrupted_no_mask() {
        // With no mask, should behave like regular transposition
        let cipher = Disrupted::<NoMask>::new("SUBWAY").unwrap();
        let plaintext = b"ATTACKATDAWN";
        let mut ciphertext = vec![0u8; plaintext.len()];
        let n = cipher.encrypt(&mut ciphertext, plaintext);
        assert_eq!(n, plaintext.len());

        let mut decrypted = vec![0u8; plaintext.len()];
        let n2 = cipher.decrypt(&mut decrypted, &ciphertext);
        assert_eq!(n2, plaintext.len());
        assert_eq!(&decrypted, plaintext);
    }

    #[test]
    fn test_disrupted_vic_mask() {
        // VIC-style triangular mask
        let cipher = Disrupted::<VicMask>::new("SUBWAY").unwrap();
        let plaintext = b"ATTACKATDAWN";
        let mut ciphertext = vec![0u8; plaintext.len()];
        let n = cipher.encrypt(&mut ciphertext, plaintext);
        assert_eq!(n, plaintext.len());

        let mut decrypted = vec![0u8; plaintext.len()];
        let n2 = cipher.decrypt(&mut decrypted, &ciphertext);
        assert_eq!(n2, plaintext.len());
        assert_eq!(&decrypted, plaintext);
    }

    #[test]
    fn test_disrupted_secom_mask() {
        // SECOM-style disrupted mask
        let cipher = Disrupted::<SecomMask>::new("SUBWAY").unwrap();
        let plaintext = b"HELLOWORLD";
        let mut ciphertext = vec![0u8; plaintext.len()];
        let n = cipher.encrypt(&mut ciphertext, plaintext);
        assert_eq!(n, plaintext.len());

        let mut decrypted = vec![0u8; plaintext.len()];
        let n2 = cipher.decrypt(&mut decrypted, &ciphertext);
        assert_eq!(n2, plaintext.len());
        assert_eq!(&decrypted, plaintext);
    }

    #[test]
    fn test_disrupted_longer_text() {
        let cipher = Disrupted::<VicMask>::new("ARABESQUE").unwrap();
        let plaintext = b"THEQUICKBROWNFOXJUMPSOVERTHELAZYDOG";
        let mut ciphertext = vec![0u8; plaintext.len()];
        let n = cipher.encrypt(&mut ciphertext, plaintext);
        assert_eq!(n, plaintext.len());

        let mut decrypted = vec![0u8; plaintext.len()];
        let n2 = cipher.decrypt(&mut decrypted, &ciphertext);
        assert_eq!(n2, plaintext.len());
        assert_eq!(&decrypted, plaintext);
    }

    #[test]
    fn test_disrupted_irregular_length() {
        // Test with length not divisible by key length
        let cipher = Disrupted::<SecomMask>::new("KEY").unwrap();
        let plaintext = b"HELLO";
        let mut ciphertext = vec![0u8; plaintext.len()];
        let n = cipher.encrypt(&mut ciphertext, plaintext);
        assert_eq!(n, plaintext.len());

        let mut decrypted = vec![0u8; plaintext.len()];
        let n2 = cipher.decrypt(&mut decrypted, &ciphertext);
        assert_eq!(n2, plaintext.len());
        assert_eq!(&decrypted, plaintext);
    }

    #[test]
    fn test_disrupted_empty_key() {
        let result = Disrupted::<NoMask>::new("");
        assert!(result.is_err());
    }

    #[test]
    fn test_disrupted_block_size() {
        let cipher = Disrupted::<NoMask>::new("SUBWAY").unwrap();
        assert_eq!(cipher.block_size(), 6);

        let cipher = Disrupted::<NoMask>::new("KEY").unwrap();
        assert_eq!(cipher.block_size(), 3);
    }
}